/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as DataRouteImport } from './routes/data'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPermohonanIdRouteImport } from './routes/admin.permohonan.$id'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermohonanIdRoute = AdminPermohonanIdRouteImport.update({
  id: '/admin/permohonan/$id',
  path: '/admin/permohonan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/data': typeof DataRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/tentang': typeof TentangRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/permohonan/$id': typeof AdminPermohonanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/data': typeof DataRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AdminIndexRoute
  '/admin/permohonan/$id': typeof AdminPermohonanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/data': typeof DataRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/tentang': typeof TentangRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/permohonan/$id': typeof AdminPermohonanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berita'
    | '/data'
    | '/kontak'
    | '/layanan'
    | '/tentang'
    | '/admin/'
    | '/admin/permohonan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berita'
    | '/data'
    | '/kontak'
    | '/layanan'
    | '/tentang'
    | '/admin'
    | '/admin/permohonan/$id'
  id:
    | '__root__'
    | '/'
    | '/berita'
    | '/data'
    | '/kontak'
    | '/layanan'
    | '/tentang'
    | '/admin/'
    | '/admin/permohonan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeritaRoute: typeof BeritaRoute
  DataRoute: typeof DataRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  TentangRoute: typeof TentangRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPermohonanIdRoute: typeof AdminPermohonanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permohonan/$id': {
      id: '/admin/permohonan/$id'
      path: '/admin/permohonan/$id'
      fullPath: '/admin/permohonan/$id'
      preLoaderRoute: typeof AdminPermohonanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeritaRoute: BeritaRoute,
  DataRoute: DataRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  TentangRoute: TentangRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPermohonanIdRoute: AdminPermohonanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
